#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
MRF-based object geolocation from Amsterdam inference detections.

Input:
    Ams_All.csv generated by run_amsterdam_inference.py

Expected columns:
    Fname, Pix, ObjBearing, Lon, Lat, Depth, RFov, LFov, Captured_at

Outputs:
    final_geolocations.csv
    final_geolocation_pairs.csv
    admissible_intersections.csv
    selected_intersections.csv
"""

from __future__ import annotations

import argparse
import csv
import time
from dataclasses import dataclass
from math import asin, atan2, cos, degrees, radians, sin, sqrt
from pathlib import Path
from typing import List, Optional, Sequence, Tuple

import numpy as np
import pandas as pd
from scipy.cluster.hierarchy import fcluster, linkage

try:
    from pystruct import inference
except ImportError:
    inference = None


@dataclass
class Detection:
    """Single positive image/view detection."""

    index: int
    fname: str
    bearing: float
    cam_lon: float
    cam_lat: float
    depth: float
    rfov: Optional[float] = None
    lfov: Optional[float] = None
    captured_at: Optional[str] = None
    ray_lat_1m: float = 0.0
    ray_lon_1m: float = 0.0
    depth_lat: float = 0.0
    depth_lon: float = 0.0


@dataclass
class IntersectionRecord:
    """Pairwise ray intersection between two detections."""

    det_i: int
    det_j: int
    lat: float
    lon: float
    dist_i: float
    dist_j: float


@dataclass
class MRFConfig:
    """Configuration for MRF geolocation."""

    input_csv: Path
    output_dir: Path
    max_object_distance_m: float = 30.0
    min_camera_distance_m: float = 0.5
    max_camera_distance_factor: float = 1.5
    max_cluster_distance_m: float = 8.0
    default_depth_m: float = 7.5
    depth_weight: float = 0.01
    object_multiview_weight: float = 0.25
    standalone_price: float = 0.3
    distance_power: float = 1.0


def haversine_m(lon1: float, lat1: float, lon2: float, lat2: float) -> float:
    """Great-circle distance between two WGS84 coordinates in metres."""
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat / 2.0) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2.0) ** 2
    c = 2.0 * asin(sqrt(a))
    return 6_367_000.0 * c


def haversine_latlon(a: Sequence[float], b: Sequence[float]) -> float:
    """Distance function for clustering, where points are [lat, lon]."""
    return haversine_m(a[1], a[0], b[1], b[0])


def shift_latlon(lat: float, lon: float, bearing_deg: float, distance_m: float) -> Tuple[float, float]:
    """Move from a source coordinate along a bearing by a given distance."""
    earth_radius_km = 6378.1
    bearing = radians(bearing_deg)
    distance_km = distance_m / 1000.0
    lat1 = radians(lat)
    lon1 = radians(lon)

    lat2 = asin(
        sin(lat1) * cos(distance_km / earth_radius_km)
        + cos(lat1) * sin(distance_km / earth_radius_km) * cos(bearing)
    )
    lon2 = lon1 + atan2(
        sin(bearing) * sin(distance_km / earth_radius_km) * cos(lat1),
        cos(distance_km / earth_radius_km) - sin(lat1) * sin(lat2),
    )
    return degrees(lat2), degrees(lon2)


def parse_float(value, default: Optional[float] = None) -> Optional[float]:
    """Parse a float from a CSV value, handling blanks and NaNs."""
    if value is None or pd.isna(value):
        return default
    value_str = str(value).strip()
    if value_str == "":
        return default
    try:
        return float(value_str)
    except ValueError:
        return default


def load_ams_detections(config: MRFConfig) -> List[Detection]:
    """Load detections from Ams_All.csv."""
    df = pd.read_csv(config.input_csv)
    df.columns = [c.strip() for c in df.columns]

    required_columns = ["Fname", "ObjBearing", "Lon", "Lat"]
    missing = [col for col in required_columns if col not in df.columns]
    if missing:
        raise ValueError(
            f"Missing columns in input CSV: {missing}. Available columns: {list(df.columns)}"
        )

    detections: List[Detection] = []
    for _, row in df.iterrows():
        fname = str(row["Fname"]).strip()
        bearing = parse_float(row.get("ObjBearing"))
        lon = parse_float(row.get("Lon"))
        lat = parse_float(row.get("Lat"))

        if fname == "" or bearing is None or lon is None or lat is None:
            continue

        depth = parse_float(row.get("Depth"), default=config.default_depth_m)
        if depth is None or depth <= 0:
            depth = config.default_depth_m

        rfov = parse_float(row.get("RFov"), default=None)
        lfov = parse_float(row.get("LFov"), default=None)
        captured_at = str(row.get("Captured_at", "")).strip()

        ray_lat_1m, ray_lon_1m = shift_latlon(lat, lon, bearing, 1.0)
        depth_lat, depth_lon = shift_latlon(lat, lon, bearing, depth)

        detections.append(
            Detection(
                index=len(detections),
                fname=fname,
                bearing=bearing,
                cam_lon=lon,
                cam_lat=lat,
                depth=depth,
                rfov=rfov,
                lfov=lfov,
                captured_at=captured_at,
                ray_lat_1m=ray_lat_1m,
                ray_lon_1m=ray_lon_1m,
                depth_lat=depth_lat,
                depth_lon=depth_lon,
            )
        )
    return detections


def intersect_two_rays(
    det1: Detection,
    det2: Detection,
    max_object_distance_m: float,
) -> Optional[IntersectionRecord]:
    """Calculate the intersection between two camera rays."""
    lat_c1, lon_c1 = det1.cam_lat, det1.cam_lon
    lat_c2, lon_c2 = det2.cam_lat, det2.cam_lon
    lat_p1, lon_p1 = det1.ray_lat_1m, det1.ray_lon_1m
    lat_p2, lon_p2 = det2.ray_lat_1m, det2.ray_lon_1m

    a1 = lat_p1 - lat_c1
    b1 = lat_p2 - lat_c2
    c1 = lat_c2 - lat_c1
    a2 = lon_p1 - lon_c1
    b2 = lon_p2 - lon_c2
    c2 = lon_c2 - lon_c1

    denominator = a2 * b1 - b2 * a1
    if denominator == 0:
        return None

    dist_j = (a1 * c2 - a2 * c1) / denominator
    if a1 != 0:
        dist_i = (b1 * dist_j + c1) / a1
    elif a2 != 0:
        dist_i = (b2 * dist_j + c2) / a2
    else:
        return None

    if dist_i < 0 or dist_j < 0:
        return None
    if dist_i > max_object_distance_m or dist_j > max_object_distance_m:
        return None

    intersect_lat = a1 * dist_i + lat_c1
    intersect_lon = a2 * dist_i + lon_c1

    return IntersectionRecord(
        det_i=det1.index,
        det_j=det2.index,
        lat=float(intersect_lat),
        lon=float(intersect_lon),
        dist_i=float(dist_i),
        dist_j=float(dist_j),
    )


def build_pairwise_intersections(
    detections: List[Detection],
    config: MRFConfig,
) -> Tuple[np.ndarray, np.ndarray, List[IntersectionRecord]]:
    """Build pairwise distance and intersection matrices."""
    n = len(detections)
    objects_dst = np.zeros((n, n), dtype=np.float64)
    intersections = np.zeros((n, n, 2), dtype=np.float64)
    records: List[IntersectionRecord] = []
    max_camera_distance_m = config.max_camera_distance_factor * config.max_object_distance_m

    for i in range(n):
        objects_dst[i, i] = -5.0
        if i % 1000 == 0 and i > 0:
            print(f"Parsed {i} detections ({100.0 * i / n:.2f}%)")

        for j in range(i + 1, n):
            det_i = detections[i]
            det_j = detections[j]

            cam_distance = haversine_m(det_i.cam_lon, det_i.cam_lat, det_j.cam_lon, det_j.cam_lat)
            if cam_distance < config.min_camera_distance_m or cam_distance > max_camera_distance_m:
                objects_dst[i, j] = -4.0
                objects_dst[j, i] = -4.0
                continue

            record = intersect_two_rays(det_i, det_j, config.max_object_distance_m)
            if record is None:
                objects_dst[i, j] = -1.0
                objects_dst[j, i] = -1.0
                continue

            objects_dst[i, j] = record.dist_i
            objects_dst[j, i] = record.dist_j
            intersections[i, j, 0] = record.lat
            intersections[i, j, 1] = record.lon
            intersections[j, i, 0] = record.lat
            intersections[j, i, 1] = record.lon
            records.append(record)

    return objects_dst, intersections, records


def run_mrf_selection(
    detections: List[Detection],
    objects_dst: np.ndarray,
    intersections: np.ndarray,
    config: MRFConfig,
) -> List[IntersectionRecord]:
    """Run MRF optimization and return selected pairwise intersections."""
    if inference is None:
        raise ImportError(
            "pystruct is required for MRF optimization. Install pystruct before running this script."
        )

    xall: List[Tuple[int, int]] = []
    xall_index = np.zeros((len(detections), len(detections)), dtype=np.int32)
    unary_terms: List[float] = []
    pairwise_edges_raw: List[Tuple[int, int, int]] = []
    pairwise_terms: List[float] = []
    xall_count = 0

    for i in range(len(detections)):
        ray_candidates = []
        num_candidates_for_i = np.count_nonzero(objects_dst[i, :] > 0)
        if num_candidates_for_i == 0:
            continue

        for j in range(i + 1, len(detections)):
            if objects_dst[i, j] <= 0:
                continue

            ray_candidates.append(j)
            xall.append((i, j))
            xall_index[i, j] = xall_count
            xall_count += 1

            depth_term = config.depth_weight * (
                abs(objects_dst[i, j] - detections[i].depth) ** config.distance_power
                + abs(objects_dst[j, i] - detections[j].depth) ** config.distance_power
            )
            standalone_term = config.standalone_price / (
                num_candidates_for_i ** (1.0 / config.distance_power)
            )
            unary_terms.append(depth_term - standalone_term)

        for jj in range(len(ray_candidates)):
            for kk in range(jj + 1, len(ray_candidates)):
                j = ray_candidates[jj]
                k = ray_candidates[kk]
                pairwise_edges_raw.append((i, j, k))

                same_camera = (
                    detections[j].cam_lat == detections[k].cam_lat
                    and detections[j].cam_lon == detections[k].cam_lon
                )
                if same_camera:
                    pairwise_terms.append(10000.0)
                else:
                    pairwise_terms.append(
                        config.object_multiview_weight
                        * abs(objects_dst[i, j] - objects_dst[i, k]) ** 2
                    )

    n_nodes = len(xall)
    n_edges = len(pairwise_edges_raw)
    n_states = 2
    if n_nodes == 0:
        return []

    unary_potentials = np.zeros((n_nodes, n_states), dtype=np.float64)
    for idx, value in enumerate(unary_terms):
        unary_potentials[idx, 0] = 0.0
        unary_potentials[idx, 1] = -value

    pairwise_potentials = np.zeros((2 * n_edges, n_states, n_states), dtype=np.float64)
    edges = np.zeros((2 * n_edges, 2), dtype=np.int32)

    for edge_idx, raw_edge in enumerate(pairwise_edges_raw):
        i, j, k = raw_edge
        pairwise_potentials[2 * edge_idx, 1, 1] = -pairwise_terms[edge_idx]
        pairwise_potentials[2 * edge_idx + 1, 1, 1] = -pairwise_terms[edge_idx]

        node_a = xall_index[i, j]
        node_b = xall_index[i, k]
        edges[2 * edge_idx, 0] = node_a
        edges[2 * edge_idx, 1] = node_b
        edges[2 * edge_idx + 1, 0] = node_b
        edges[2 * edge_idx + 1, 1] = node_a

    print(f"Number of MRF nodes: {n_nodes}")
    print(f"Number of MRF edges: {n_edges}")
    start = time.time()
    labels = inference.inference_dispatch(
        unary_potentials,
        pairwise_potentials,
        edges,
        "qpbo",
        {},
    )
    print(f"MRF solved in {time.time() - start:.2f} seconds.")

    selected: List[IntersectionRecord] = []
    for node_idx, label in enumerate(labels):
        if label != 1:
            continue
        i, j = xall[node_idx]
        selected.append(
            IntersectionRecord(
                det_i=i,
                det_j=j,
                lat=float(intersections[i, j, 0]),
                lon=float(intersections[i, j, 1]),
                dist_i=float(objects_dst[i, j]),
                dist_j=float(objects_dst[j, i]),
            )
        )
    return selected


def cluster_intersections(
    selected: List[IntersectionRecord],
    max_cluster_distance_m: float,
) -> Tuple[np.ndarray, np.ndarray]:
    """Cluster selected intersections using hierarchical clustering."""
    if len(selected) == 0:
        return np.empty((0, 4)), np.empty((0,), dtype=np.int32)

    points = np.asarray([[rec.lat, rec.lon] for rec in selected], dtype=np.float64)
    if len(points) == 1:
        return np.asarray([[0, points[0, 0], points[0, 1], 1]], dtype=np.float64), np.asarray([0])

    z = linkage(points, metric=haversine_latlon)
    labels = fcluster(z, max_cluster_distance_m, criterion="distance") - 1
    num_clusters = int(labels.max()) + 1
    cluster_summary = np.zeros((num_clusters, 4), dtype=np.float64)

    for cluster_id in range(num_clusters):
        cluster_points = points[labels == cluster_id]
        cluster_summary[cluster_id, 0] = cluster_id
        cluster_summary[cluster_id, 1] = np.mean(cluster_points[:, 0])
        cluster_summary[cluster_id, 2] = np.mean(cluster_points[:, 1])
        cluster_summary[cluster_id, 3] = len(cluster_points)

    return cluster_summary, labels.astype(np.int32)


def write_detection_debug_files(detections: List[Detection], output_dir: Path) -> None:
    """Write optional debug files showing ray and depth endpoints."""
    with open(output_dir / "detection_ray_1m_points.csv", "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["det_id", "fname", "lat", "lon", "depth_m"])
        for det in detections:
            writer.writerow([det.index, det.fname, det.ray_lat_1m, det.ray_lon_1m, det.depth])

    with open(output_dir / "detection_depth_points.csv", "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["det_id", "fname", "lat", "lon", "depth_m"])
        for det in detections:
            writer.writerow([det.index, det.fname, det.depth_lat, det.depth_lon, det.depth])


def write_intersections(records: List[IntersectionRecord], detections: List[Detection], output_path: Path) -> None:
    """Write intersection records with supporting image-pair information."""
    with open(output_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "det_i", "det_j", "fname_i", "fname_j",
            "intersect_lat", "intersect_lon", "dist_i_m", "dist_j_m",
            "cam_lat_i", "cam_lon_i", "cam_lat_j", "cam_lon_j",
            "bearing_i", "bearing_j",
        ])
        for rec in records:
            det_i = detections[rec.det_i]
            det_j = detections[rec.det_j]
            writer.writerow([
                rec.det_i, rec.det_j, det_i.fname, det_j.fname,
                rec.lat, rec.lon, rec.dist_i, rec.dist_j,
                det_i.cam_lat, det_i.cam_lon, det_j.cam_lat, det_j.cam_lon,
                det_i.bearing, det_j.bearing,
            ])


def write_final_geolocations(cluster_summary: np.ndarray, output_path: Path) -> None:
    """Write final clustered geolocations."""
    with open(output_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["cluster_id", "lat", "lon", "score"])
        for row in cluster_summary:
            writer.writerow([int(row[0]), row[1], row[2], int(row[3])])


def write_cluster_pairs(
    selected: List[IntersectionRecord],
    cluster_labels: np.ndarray,
    detections: List[Detection],
    output_path: Path,
) -> None:
    """Write image/view pairs supporting each final geolocation."""
    with open(output_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow([
            "cluster_id", "det_i", "det_j", "fname_i", "fname_j",
            "intersect_lat", "intersect_lon", "dist_i_m", "dist_j_m",
            "cam_lat_i", "cam_lon_i", "cam_lat_j", "cam_lon_j",
            "bearing_i", "bearing_j", "captured_at_i", "captured_at_j",
        ])
        for rec, cluster_id in zip(selected, cluster_labels):
            det_i = detections[rec.det_i]
            det_j = detections[rec.det_j]
            writer.writerow([
                int(cluster_id), rec.det_i, rec.det_j, det_i.fname, det_j.fname,
                rec.lat, rec.lon, rec.dist_i, rec.dist_j,
                det_i.cam_lat, det_i.cam_lon, det_j.cam_lat, det_j.cam_lon,
                det_i.bearing, det_j.bearing, det_i.captured_at, det_j.captured_at,
            ])


def run_geolocation(config: MRFConfig) -> None:
    """Run complete MRF geolocation pipeline."""
    config.output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Reading detections from: {config.input_csv}")
    detections = load_ams_detections(config)
    print(f"Loaded detections: {len(detections)}")

    if len(detections) < 2:
        print("At least two detections are required for pairwise geolocation.")
        return

    write_detection_debug_files(detections, config.output_dir)

    print("Building pairwise ray intersections...")
    objects_dst, intersections, admissible = build_pairwise_intersections(detections, config)
    print(f"Admissible intersections: {len(admissible)}")
    write_intersections(admissible, detections, config.output_dir / "admissible_intersections.csv")

    print("Running MRF optimization...")
    selected = run_mrf_selection(detections, objects_dst, intersections, config)
    print(f"MRF-selected intersections: {len(selected)}")
    write_intersections(selected, detections, config.output_dir / "selected_intersections.csv")

    print("Clustering selected intersections...")
    cluster_summary, cluster_labels = cluster_intersections(selected, config.max_cluster_distance_m)
    print(f"Final geolocation clusters: {len(cluster_summary)}")

    write_final_geolocations(cluster_summary, config.output_dir / "final_geolocations.csv")
    write_cluster_pairs(selected, cluster_labels, detections, config.output_dir / "final_geolocation_pairs.csv")

    print("Process completed.")
    print(f"Final geolocations saved to: {config.output_dir / 'final_geolocations.csv'}")
    print(f"Supporting pairs saved to: {config.output_dir / 'final_geolocation_pairs.csv'}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate final object geolocations from Ams_All.csv using MRF optimization."
    )
    parser.add_argument("--input-csv", type=str, required=True, help="Path to Ams_All.csv.")
    parser.add_argument("--output-dir", type=str, required=True, help="Directory for outputs.")
    parser.add_argument("--max-object-distance-m", type=float, default=30.0)
    parser.add_argument("--max-cluster-distance-m", type=float, default=8.0)
    parser.add_argument("--default-depth-m", type=float, default=7.5)
    parser.add_argument("--depth-weight", type=float, default=0.01)
    parser.add_argument("--object-multiview-weight", type=float, default=0.25)
    parser.add_argument("--standalone-price", type=float, default=0.3)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    config = MRFConfig(
        input_csv=Path(args.input_csv),
        output_dir=Path(args.output_dir),
        max_object_distance_m=args.max_object_distance_m,
        max_cluster_distance_m=args.max_cluster_distance_m,
        default_depth_m=args.default_depth_m,
        depth_weight=args.depth_weight,
        object_multiview_weight=args.object_multiview_weight,
        standalone_price=args.standalone_price,
    )
    run_geolocation(config)


if __name__ == "__main__":
    main()
